import SEKernel
#print axioms SEKernel.Law1.selection_gain
#print axioms SEKernel.Law1.price_decomposition
#print axioms SEKernel.Law1.SS1_discrete
#print axioms SEKernel.Law1.SS1_equality_iff
#print axioms SEKernel.Law1.variance_eq_zero_iff
#print axioms SEKernel.Law1.elimination_single_decay
#print axioms SEKernel.Law1.elimination_single_tendsto
#print axioms SEKernel.Law1.elimination_mixture
#print axioms SEKernel.Law1.elimination_mixture_tendsto
#print axioms SEKernel.Law1.frontier_support
#print axioms SEKernel.Law1.basin_decrease
#print axioms SEKernel.Law1.basin_instability
#print axioms SEKernel.Law1.basin_no_recovery
#print axioms SEKernel.Law2.KKT.isLPOptimal
#print axioms SEKernel.Law2.KKT_of_optimal_dual
#print axioms SEKernel.Law2.KKT.reduced_return
#print axioms SEKernel.Law2.esdi_exists_const
#print axioms SEKernel.Law2.constraint_role_sparsity
#print axioms SEKernel.SmallGain.SmallGainCert.of_colSums
#print axioms SEKernel.SmallGain.G1_weight_pos
#print axioms SEKernel.SmallGain.G1_weighted_lyapunov
#print axioms SEKernel.SmallGain.G1_weighted_lyapunov_nonneg
#print axioms SEKernel.SmallGain.extension_cert
#print axioms SEKernel.SmallGain.extension_cert_halfMargin
#print axioms SEKernel.SmallGain.slack_budget
#print axioms SEKernel.SmallGain.safe_stack_depth
#print axioms SEKernel.SmallGain.no_infinite_regress
#print axioms SEKernel.Law5.PriceSupported.value_eq
#print axioms SEKernel.Law5.PriceSupported.value_le
#print axioms SEKernel.Law5.first_welfare
#print axioms SEKernel.Law5.shadow_price_implementation
#print axioms SEKernel.Law5.poa_bound
#print axioms SEKernel.Law5.poa_bound_ratio
#print axioms SEKernel.Law6.lie_identity
#print axioms SEKernel.Law6.hasDerivAt_qform_along_linear
#print axioms SEKernel.Law6.msg_sufficiency
#print axioms SEKernel.Law6.msg_necessity
#print axioms SEKernel.Law6.msg_maximal
#print axioms SEKernel.Law6.lyapunov_destruction
#print axioms SEKernel.Law6.alignment_impossibility_escape
#print axioms SEKernel.Law6.admissible_foldr
#print axioms SEKernel.Law6.admissible_unique
#print axioms SEKernel.Law6.endogenous_electorate_impossibility
#print axioms SEKernel.Law6.majority_spawnManipulable
#print axioms SEKernel.Law6.majority_not_populationStable
#print axioms SEKernel.Law2.equilibrium_of_le_mean
#print axioms SEKernel.Law2.exists_mean_maximizer
#print axioms SEKernel.Law2.maximizer_method_gap
#print axioms SEKernel.Law2.nashMap_fixedPoint_equilibrium
#print axioms SEKernel.Law2.esdi_exists_of_fixedPoint
#print axioms SEKernel.Law6.neutrality_unsat_three
#print axioms SEKernel.SpectralBridge.eigenvalue_le_rowSum
#print axioms SEKernel.SpectralBridge.gain_eigenvalue_bound
#print axioms SEKernel.SpectralBridge.extension_eigenvalue_bound
#print axioms SEKernel.Law7.hopfCurve_pos
#print axioms SEKernel.Law7.firstLyapunov_neg
#print axioms SEKernel.Law7.hopf_transition_conditional
#print axioms SEKernel.Law6.neutrality_unsat
#print axioms SEKernel.Law6.spawnManipulable_of_overwhelmingBloc
#print axioms SEKernel.Law6.endogenous_electorate_impossibility_repaired
#print axioms SEKernel.Law6.majority_overwhelmingBloc
#print axioms SEKernel.Law6.majority_not_populationStable_repaired
#print axioms SEKernel.Law7.rm_diag0
#print axioms SEKernel.Law7.rm_diag1
#print axioms SEKernel.Law7.rm_center_trace
#print axioms SEKernel.Law7.rm_no_hopf
#print axioms SEKernel.Law7.hopfCurve_root
#print axioms SEKernel.Law7.rm_offdiag01
#print axioms SEKernel.Law7.rm_offdiag10
#print axioms SEKernel.Law7.rm_center_det
#print axioms SEKernel.Law7.rm_trace_transversal
#print axioms SEKernel.Law7.rm_true_hopf
#print axioms SEKernel.Law7.swirl_ratio_blowup
#print axioms SEKernel.PriceMarket.replication_wedge
#print axioms SEKernel.PriceMarket.spawnProof_iff_fnp
#print axioms SEKernel.PriceMarket.no_beneficial_spawn_of_fnp
#print axioms SEKernel.PriceMarket.cap_iff
#print axioms SEKernel.PriceMarket.cap_mono
#print axioms SEKernel.PriceMarket.cap_collapse
#print axioms SEKernel.PriceMarket.Market.efficient_iff_zero
#print axioms SEKernel.PriceMarket.Market.zero_nashEq_iff_fnp
#print axioms SEKernel.PriceMarket.Market.efficient_nashEq_iff_fnp
#print axioms SEKernel.PriceMarket.Market.spawn_inefficient
#print axioms SEKernel.PriceMarket.Market.fnp_of_marginal
#print axioms SEKernel.PriceMarketMaster.qf_split
#print axioms SEKernel.PriceMarketMaster.qf_rewards_splitting
#print axioms SEKernel.PriceMarketMaster.lin_split
#print axioms SEKernel.PriceMarketMaster.qf_defeats_large_market
#print axioms SEKernel.PriceMarketMaster.coupled_hopf
#print axioms SEKernel.PriceMarketMaster.coupled_transversal
#print axioms SEKernel.PriceMarketMaster.coupled_imaginary_onset
#print axioms SEKernel.PriceMarketMaster.coupled_supercritical
#print axioms SEKernel.WaterLine.waterLine_scalar_certificates
#print axioms SEKernel.WaterLine.waterLine_sum_of_squares
#print axioms SEKernel.WaterLine.waterLine_kkt_sufficient
#print axioms SEKernel.WaterLine.barbell_coefficients
#print axioms SEKernel.WaterLine.barbell_gap_solution
#print axioms SEKernel.WaterLine.barbell_constant_deployment_binding
#print axioms SEKernel.WaterLine.barbell_active_gaps
#print axioms SEKernel.WaterLine.barbell_inactive_gap_identity
#print axioms SEKernel.WaterLine.barbell_inactive_gap_strict
#print axioms SEKernel.WaterLine.barbell_all_inactive_gaps
#print axioms SEKernel.WaterLine.affine_multiplier_positive_below_threshold
#print axioms SEKernel.WaterLine.cournot_markup_identity
#print axioms SEKernel.WaterLine.cournot_markup_single_principal
#print axioms SEKernel.WaterLine.pseudoGradient_monotonicity_identity
#print axioms SEKernel.WaterLine.pseudoGradient_strict_monotonicity
#print axioms SEKernel.SpawnConflict.quadratic_expansion_identity
#print axioms SEKernel.SpawnConflict.phiQ_separable
#print axioms SEKernel.SpawnConflict.userCostElimination
#print axioms SEKernel.SpawnConflict.userCostElimination_uncoupled
#print axioms SEKernel.SpawnConflict.userCostElimination_tullock
#print axioms SEKernel.SpawnConflict.lane_diagonalization
#print axioms SEKernel.SpawnConflict.lane_system_diagonalization
#print axioms SEKernel.SpawnConflict.lane_slope_formulas
#print axioms SEKernel.SpawnConflict.riccatiPolynomialEquiv
#print axioms SEKernel.SpawnConflict.noThresholdStability
#print axioms SEKernel.SpawnConflict.riccatiCollapse
#print axioms SEKernel.SpawnConflict.staticCollapse
#print axioms SEKernel.SpawnConflict.peaceTriggerThreshold
#print axioms SEKernel.SpawnConflict.dissipation_gap_identity
#print axioms SEKernel.SpawnConflict.dissipation_bound
#print axioms SEKernel.SpawnConflict.dissipation_bound_strict
